import React, { useState } from "react";
import images from "../../utilities/images";
import Footer from "../../component/Footer";

export default function TermsOfService() {
  const [signin, setSignin] = useState(false);
  const [progress, setProgress] = useState(40);
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div className="mx-auto">
      <div
        className="p-4 bg-cover bg-center"
        style={
          {
            //   backgroundImage: `url(${images.dashboardBackground})`,
          }
        }
      >
        <div className="flex flex-col items-start justify-center">
          <div className="text-white font-semibold text-5xl border-b-4 border-lineBlue pb-1 pr-3">
            Terms of Service
          </div>

          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            {/* <p className="text-white text-opacity-50 w-full mt-2  ">
              Date Last Modified: December 20, 2023
            </p> */}
            <p className="text-white text-opacity-50 w-full mt-2 ">
              Glowskin is owned and operated by Rust Glowskin Entertainment Ltd,
              registration number HE439425, located at Thermistokli Dervi, 48,
              3rd Floor, Office 306, 1065, Nicosia, Cyprus.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Payments may be handled on behalf of Rust Glowskin Entertainment
              Ltd, registration number HE439425, located at Thermistokli Dervi,
              48, 3rd Floor, Office 306, 1065, Nicosia, Cyprus.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Thank you for reviewing these Terms and Conditions of Use (the
              “Terms of Use,” “Terms,” or “Agreement”). Glowskin Holdings
              (”Glowskin,” “We,” “Us,” or “Our”) makes https://glowskin/,
              (“Website”), its mobile application (“App”), and any other
              services (collectively “Services) available for your (“You,”
              “Your,” “User,” or “Users”) use subject to this Agreement. This
              Agreement spells out what Users can expect from Glowskin and what
              Glowskin expects from its Users.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You acknowledge and agree that by browsing or using the content,
              services and tools offered by the site, you have agreed, without
              limitation or qualification, to be bound by these terms and any
              additional requirements that may apply. If you do not agree with
              these terms, please do not use this site. these terms constitute a
              legal agreement and shall apply to your use of the site and its
              services even after termination.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Your access to the Website and your right to use the Services is
              for only for personal use and for entertainment purposes only. The
              sole purpose of the Website and Services is to play games and/or
              access features on the Website.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              All outcomes on the Site are generated by our provably fair system
              and awarded as such. You agree that the outcome will be determined
              by the provably fair system and any user interface errors do not
              entitle you to an item offered on the Site.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              The Glowskin Privacy Policy is an integral part of this Agreement
              and is expressly incorporated by reference. The Glowskin Privacy
              Policy explains how Glowskin collects and protects information
              about Users who use Glowskin and can be viewed at
              https://glowskin//privacy.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Please read this Agreement carefully before creating a Glowskin
              account (“Account”), downloading the App, using the Website, or
              participating in Glowskin. Any questions regarding the Terms or
              the Privacy Policy should be directed to
              officialrustGlowskin@gmail.com.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Please note the arbitration provision set forth below, which
              requires, except where and to the extent prohibited by law, you to
              arbitrate any claims you may have against Glowskin on an
              individual basis. arbitration on an individual basis means that
              you will not have, and you waive, the right for a judge or jury to
              decide your claims, and that you may not proceed in a class,
              consolidated, or representative capacity.
            </p>
          </div>

          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              1. Acceptance of Terms
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              By downloading the App, using the Website, or participating in
              Glowskin, including, without limitation, participating in its
              games and contests (each a “Contest”), Users: (i) acknowledge that
              they have read and agree to be bound to and abide by these Terms;
              (ii) accept and agree to all obligations, rules and scoring
              systems for each Contest in which they participate; and (iii)
              represent and warrant that they are authorized and able to accept
              these Terms. Glowskin may also issue additional terms, rules and
              conditions of participation in particular Contests, which are
              expressly incorporated by reference. Users agree to be subject to
              them if they participate in such Contests. If a User does not wish
              to be bound by the Terms, the User must not download, access or
              use Service Glowskin By declining to accept these Terms, the User
              will be unable to participate in Glowskin, including participating
              on the activities offered through the Website.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin reserves the right to change these Terms at any time
              without prior notice to Users. If We modify these Terms, we will
              update the “Date Last Modified” and such changes will be effective
              upon posting. If We make what we determine to be material changes
              to these Terms, we will notify Users by prominently posting a
              notice on the Website and/or App or by sending a notice to the
              e-mail addresses on file. Users continued use of Glowskin
              following such changes constitutes acceptance of such changes. If
              Users do not agree to the changes, their sole remedy is to cease
              using Glowskin. If Users breach any of the Terms, their
              authorization to use Glowskin automatically terminates.
            </p>
          </div>

          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              2. Age Restrictions
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              No individual under the age of eighteen (18), or under the age of
              majority in your jurisdiction, may use Glowskin, regardless of any
              consent from a parent or guardian to use Glowskin. You need a
              supported Web browser to access Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              We offer our Services in the United States, with the exception of
              the states of Nevada and Washington state. You may not access our
              Website from Nevada and Washington. You are not eligible to
              participate in our Services or to win any prizes.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You are subject to the laws of the jurisdiction in which you
              reside and/or from which you access Glowskin. Void where
              prohibited or restricted by law. To be eligible to enter any
              contest or receive any prize, you may be required to provide
              Glowskin with additional documentation and/or information to
              verify your identity and to provide proof that all eligibility
              requirements are met. In the event of a dispute as to the identity
              or eligibility of a user, Glowskin will, in its sole and absolute
              discretion, utilize certain information collected by Glowskin to
              assist in verifying the identity and/or eligibility of such user.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin makes no representations or warranties, implicit or
              explicit, as to your legal right to participate in the Glowskin or
              that the contests provided through Glowskin are appropriate or
              available for use in the jurisdiction in which you are located,
              nor shall any person affiliated, or claiming affiliation, with
              Glowskin have authority to make any such representations or
              warranties. We do not intend for Glowskin or any offerings made
              available thereon to be used by persons present in jurisdictions
              in which participation may be prohibited or restricted. You agree
              that the availability of Glowskin does not constitute an offer,
              solicitation or invitation by us for the use of the Glowskin in
              any jurisdiction in which such activities are prohibited or
              restricted. If you choose to access our Service, you do so at your
              own risk. You hereby agree that Glowskin cannot be held liable if
              laws applicable to you restrict or prohibit your participation. If
              you open an Account and/or participate in contests made available
              by Glowskin while located in a jurisdiction that prohibits such
              activities, you will be in violation of the law of such
              jurisdiction and these Terms, and subject to having Your Account
              suspended or terminated.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              By inputting a payment method to participate in the contests, you
              hereby affirm that you are the lawful owner of the payment method
              account used to make any deposit(s). It shall be a violation of
              these Terms of Use for any registered user to submit payment using
              any payment method that is not owned by the user.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin reserves the right to deny access to Glowskin to anyone
              at our sole discretion
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              3. Accounts
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Only one (1) Account is allowed per person. In the event that
              Glowskin determines that You have registered more than one (1)
              Account, then You acknowledge and agree that, in addition to any
              other rights that Glowskin may have, Glowskin has the right to
              suspend or terminate Your Account(s), refuse any and all current
              or future use of Glowskin, and withhold or revoke the awarding of
              any prizes.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You are responsible for maintaining the confidentiality of your
              login names and passwords. It shall be a violation of these Terms
              of Use to allow any other person to use your account to
              participate in any contest. If you have reason to believe that
              someone is using your account without your permission, you should
              contact us immediately. We will not be responsible for any loss or
              damage resulting from your failure to notify us of unauthorized
              use. If we request registration information from you, you must
              provide us with accurate and complete information and must update
              the information when it changes.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              4. No Transfer
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Your Account is not transferable. Under no circumstances shall You
              allow or permit any other person or third-party, including,
              without limitation, any person under the age of eighteen (18), to
              use or re-use Your Account in such a way that may breach the
              standards or laws in any jurisdiction where You are located and/or
              are a resident, or where such other person is located and/or is a
              resident. You accept full responsibility for any unauthorized use
              of Glowskin and for any use of Your Account by any other person or
              third-party in connection with Your Account. Any person found to
              have violated this section may be reported to the relevant
              authorities and will forfeit their Account. Glowskin will not be
              liable for any loss that You may incur as a result of someone else
              using Your Account, either with or without Your knowledge, unless
              You have previously notified Glowskin as provided herein that Your
              Identifiers are no longer secure and confidential. In the absence
              of prior notification to Glowskin that Your Identifiers are no
              longer secure and confidential, you will be liable for losses
              incurred due to someone else using Your Account.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">5. Wallet</div>
            <p className="text-white text-opacity-50 w-full  ">
              By adding funds to your wallet on the Website (“Wallet”), you
              accept that the credits received (indicated by a “$” sign) have no
              real money value and that the virtual products have no real money
              value. The sole purpose for buying virtual items is to play games
              on the Website. We do not issue refunds for virtual products once
              the order is confirmed and the product is sent. If you experience
              any issues receiving or downloading any products purchased on the
              Website, please contact us at officialrustGlowskin@gmail.com.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              The Website is not a banking institution. Replenishment of funds
              for your Wallet is carried out through a third-party payment
              system for receiving payments and is not managed by us. Your
              interaction with the third-party payment system is not governed by
              us and we do not address any claims that you may have with any
              third-party payment system.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Additional terms and conditions may apply to your purchases on the
              Website, all of which terms are made a part of these Terms by this
              reference. You agree to abide by such other terms and conditions,
              including where applicable representing that you are of sufficient
              legal age to use or participate in such service or feature. If
              there is a conflict between these Terms and the terms posted for
              or applicable to a specific portion of the Website or for any
              service offered on or through the Website, the latter terms shall
              control with respect to your use of that portion of the Website or
              the specific service. Glowskin may make changes to the Website,
              Services and related, or to the applicable prices for any such
              products or services, at any time.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Please note: you are able to replenish your Wallet with certain
              free credits if you are a verified Glowskin user. We offer free
              credits through claiming our Rain bonus, or claiming our free
              daily case.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              6. Browsers/Equipment
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              You acknowledge and agree that Glowskin may cease to support a
              given Web browser and that your continuous use of Glowskin will
              require you to download a supported Web browser. You also
              acknowledge and agree that the performance of Glowskin is
              incumbent on the performance of your computer equipment and your
              Internet connection. You are responsible for any fees, including
              but not limited to, Internet connection or data usage fees that
              You incur when accessing Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You agree to sign on and register for Glowskin through your Steam
              account provided by Valve Corporation. You are solely responsible
              for managing your account and password and for keeping your
              password confidential. You are also solely responsible for
              restricting access to your account. If You believe your account
              password has become compromised, you must notify us immediately at
              officialglowskin@gmail.com.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You agree that you are responsible for all activities that occur
              on your account or through the use of your password by yourself or
              by other persons.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              7. Contests and Features
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              We offer several contests and other features on the Website. You
              can participate for the chance to win prizes. Our contests are
              free to play. Our features may change from time to time, at our
              sole discretion. We reserve the right to modify or cancel contests
              at any time without notice to You. Contest rules and scoring may
              differ from contest to contest. Each of our contests are governed
              by specific rules, as may be modified from time to time, which are
              set forth in the official rules for each contest and are
              incorporated into these Terms by this reference.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You have the responsibility to review the rules prior to
              participating in any contest, and to review the rules for any
              changes. You agree to abide by the then-current rules for the
              contest(s) in which You participate. Your failure to follow the
              then-current rules for the contest(s) in which You participate
              will result in Your immediate and automatic forfeiture of the
              contest(s), and We reserve the right to immediately suspend or
              terminate Your access to Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Winners are determined by the applicable documentation associated
              with the contest. Glowskin may not be used for any form of illicit
              gambling.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You may make monetary deposits on the site and receive credits to
              purchase lootboxes. You may also receive free credits by
              participating in our rain bonus or claiming our free daily case.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              We also offer “Case Battles,” which involve between two and four
              players. All players purchase a loot box and open the boxes
              simultaneously. The player with the better item keeps that item
              and the other players’ prizes.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Upgrader is another game mode. A player selects an item they would
              like to “upgrade” to – which include any of the virtual items we
              offer. Players select the odds of winning the prize (which
              determines the cost). If a player wins, he or she can either
              choose to be credited for the value of the item or have the item
              sent directly to his or her Steam account.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Plinko – a plinko ball game where the balls fall and bounce
              through a board. Each ball can land on various multipliers.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Rain – We offer a rewards program called “rain.” A base of 25
              credits plus a percentage of all spend on the site during the
              stated time period (30 minutes) is added to each rain. Each rain
              lasts for 30 minutes. At the end of this 30-minute period, any
              user who is over level 10 or has completed the KYC on site can
              join and receive aequal share of the total pot. Rain is a reward
              for players to collect while they are actively playing on the site
              as part of our free to play system. Abusing Rain contrary to its
              intended purpose, may result in the termination of your account at
              the sole discretion of the Glowskin team.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              8. Results and Winners
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              The results and winners of each contest will be determined by Us
              at Our sole discretion and such determinations are final. We
              reserve the right to make adjustments based on errors or
              irregularities in Our calculation of results. We also may make
              adjustments in the event of noncompliance with the Terms. Any
              decision by Glowskin as to the winner(s) of a contest shall stand
              as a final and binding decision. Glowskin has no obligation to
              delay the awarding of a prize in anticipation of any adjustment,
              but We reserve the right to reverse prizes in the event of any
              adjustment. By registering an Account and/or participating in any
              contest, you unconditionally agree that Glowskin shall serve as
              the sole judge and arbiter as to the determination of a winner(s)
              in all contests in the event a dispute arises and agree to
              cooperate with Our efforts to reverse prizing, as necessary.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              We reserve the right, in our sole and absolute discretion, to deny
              any contestant the ability to participate in any contests for any
              reason whatsoever. Further, Glowskin may, in its sole and absolute
              discretion, invalidate any contest result for the purposes of
              preventing abusive and/or any unfair or potentially unlawful
              activity, or in the event that there is a risk of any such
              abusive, illegal, or unfair activity.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin also reserves the right to cancel contests, in our sole
              discretion, without any restrictions. Glowskin, in its sole
              discretion, may disqualify you from a contest or the entire
              Service, refuse to award prizes and require the return of any
              prizes, or suspend, limit, or terminate your account if you engage
              in conduct Glowskin deems, in its sole discretion, to be improper,
              unfair, fraudulent or otherwise adverse to the operation of the
              Service or in any way detrimental to other users. Improper conduct
              includes, but is not limited to: falsifying personal information,
              including payment information, required to use the Service or
              claim a prize; violating eligible payment method terms, violating
              any of these rules, accumulating points or prizes through
              unauthorized methods such as unauthorized scripts or other
              automated means; tampering with the administration of the Service
              or trying to in any way tamper with the computer programs
              associated with the Service; obtaining other entrants’ information
              and spamming or being abusive or harassing to other entrants; and
              abusing the Service in any way; or otherwise violating these Terms
              of Use. You acknowledge that the forfeiture and/or return of any
              prize shall in no way prevent Glowskin from informing the relevant
              authorities, and/or pursuing criminal or civil proceedings in
              connection with such conduct.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              If for any reason the Service is not running as originally planned
              (e.g., if the Site becomes corrupted or does not allow the proper
              usage and processing of entries in accordance with the rules, or
              if infection by a computer virus, bugs, tampering, unauthorized
              intervention, actions by entrants, fraud, technical failures, or
              any other causes of any kind, in the sole opinion of Glowskin
              corrupts or affects the administration, security, fairness,
              integrity or proper conduct of the Service), Glowskin reserves the
              right, in its sole discretion, to disqualify any individual
              implicated in or relating to the cause and/or to cancel,
              terminate, extend, modify or suspend the Service, and select the
              winner(s) from all eligible entries received. If such
              cancellation, termination, modification or suspension occurs,
              notification may be posted on the Website.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              The failure of Glowskin to comply with any provision of these
              Terms due to an act of God, for example hurricane, war, fire,
              riot, earthquake, terrorism, act of public enemies, actions of
              governmental authorities outside of the control of Glowskin
              (excepting compliance with applicable codes and regulations) or
              other force majeure event will not be considered a breach of these
              Terms.
            </p>
          </div>

          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              9. Contest Prizes; Affidavit of Eligibility and Taxes
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Contest prizes may be offered in the form of various forms. See
              the official rules for each contest for complete prize details and
              restrictions.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              No substitution or transfer of any prize is permitted except at
              Glowskin sole discretion. All prizes are awarded AS IS and WITHOUT
              WARRANTY OF ANY KIND, express or implied, (including, without
              limitation, any implied warranty of merchantability or fitness for
              a particular purpose) by Glowskin. If any legal authority
              challenges the award and/or Your receipt of a prize for winning a
              contest, we reserve the right to revoke, cancel, suspend,
              substitute, or modify the award of such prize.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Any prizes that are mistakenly credited as winnings to Your User
              Account remain Our property and will automatically be deducted
              from Your User Account upon confirmation of the error. Any
              winnings mistakenly credited to Your User Account that have been
              withdrawn by You before confirmation of the error will constitute
              a debt owed by You to Us in the amount of such wrongfully
              attributed winnings.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Prizes will only be awarded if a contest is run. We reserve the
              right to cancel contests at any time for any reason. In the event
              of a cancellation, all entry fees will be refunded to the customer
              except as specifically provided in these Terms of Use.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Each Contest or promotion is governed by its own set of official
              rules. We encourage you to read such Contest and promotions Rules
              before participating.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              10. Affidavit of Eligibility/Taxes
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              In order to receive a prize, Users may be required via e-mail or
              U.S. Mail to receive and return an executed affidavit of
              eligibility, a liability release and, where lawful, a publicity
              release (collectively, the “Affidavit”) and/or appropriate tax
              forms within seven (7) days of notification. By participating in
              the contest, you agree to receive via e-mail or U.S. Mail and
              return an executed Affidavit and/or appropriate tax forms, as
              applicable, and You agree that if such documents are not returned
              within the specified time period, or if the prize or prize
              notification is unclaimed or returned as undeliverable, or if You
              are not in compliance with these Terms, the prize will be
              forfeited and may be awarded to another potential winner at Our
              discretion. You are responsible for any and all taxes applicable
              to your receipt and use of any prizes.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              11. Prohibited Conduct
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              As a condition to your use of Glowskin, you agree not to:
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (a) falsify personal information required to open an account,
              enter a contest, or claim a prize;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (b) engage in any type of financial fraud including unauthorized
              use of credit instruments to enter a contest or claim a prize;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (c) collude with any individual in violation of these Terms;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (d) violate the contest rules or the terms of use
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (e) use a single account to participate in a contest on behalf of
              multiple entrants or otherwise collaborating with others to
              participate in any contest;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (f) impersonate or misrepresent your affiliation with any person
              or entity;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (g) access, tamper with, or use any non-public areas of Glowskin
              or Glowskin’s computer systems;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (h) attempt to probe, scan, or test the vulnerability of Glowskin
              or any related system or network or breach any security or
              authentication measures used in connection with Glowskin and such
              systems and networks;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (i) attempt to decipher, decompile, disassemble, reverse engineer
              or otherwise investigate any of the software or components used to
              provide Glowskin;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (j) harm or threaten to harm other users in any way or interfere
              with, or attempt to interfere with, the access of any user, host
              or network, including without limitation, by sending a virus,
              overloading, flooding, spamming, or mail-bombing Glowskin;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (k) provide payment information belonging to a third party;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (l) use Glowskin in an abusive way contrary to its intended use,
              to Glowskin policies and instructions and to any applicable law;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (m) systematically retrieve data or other content from Glowskin to
              create or compile, directly or indirectly, in single or multiple
              downloads, a collection, compilation, database, directory or the
              like, whether by manual methods, through the use of bots,
              crawlers, or spiders, or otherwise;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (n) infringe third party intellectual property rights when using
              or accessing Glowskin, including but not limited to in making
              available virtual items by using Glowskin; and (j) make use of,
              promote, link to or provide access to materials deemed by Glowskin
              at its sole discretion to be offensive or cause harm to Glowskin’s
              reputation, including, but not limited to, illegal content and
              pornographic content and content deemed offensive or injurious to
              Glowskin (such as Warez sites, IRC bots and BitTorrent sites).
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (o) the use of the Glowskin onsite shop to trade skins for other
              skins without playing the games.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (p) tampering with the administration of a contest or trying in
              any way to tamper with the computer programs or any security
              measure associated with a contest.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              (q) Prohibited conduct and abuse, includes; but is not limited to;
              the repeated farming of rewards contrary to their intended
              purposes. This includes but not limited to; the stacking of free
              rewards.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              12. Termination
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              We may terminate or suspend access to our Service immediately,
              without prior notice or liability, for any reason whatsoever,
              including without limitation if you breach the Terms of Service.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              All provisions of the Terms of Service which by their nature
              should survive termination shall survive termination, including,
              without limitation, ownership provisions, warranty disclaimers,
              indemnity and limitations of liability.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              We may terminate or suspend your account immediately, without
              prior notice or liability, for any reason whatsoever, including
              without limitation if you breach the Terms of Service.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Upon termination, your right to use Glowskin will immediately
              cease. Glowskin also reserves the right to suspend or terminate
              Accounts that have been inactive for one hundred eighty (180) days
              or longer. In the event that a User’s Account is terminated or
              canceled, the User will have no further access to their Account or
              anything associated with it. Users can lose their username in
              Glowskin as a result of Account termination or cancellation. If
              Your Account is suspended or terminated by Us for a violation of
              the Terms, we reserve the right to determine whether to funds to
              defray the costs of administration and enforcement of the Terms.
              If Your Account is subject to a suspension or termination, you
              must respect the restrictions and limitations imposed on Your
              Account as part of the suspension or termination.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              If you wish to terminate your account, you may contact us at
              officialglowskin@gmail.com.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">13. DMCA</div>
            <p className="text-white text-opacity-50 w-full  ">
              Monitoring and Copyright Complaints
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You agree that Glowskin has the right, but not the obligation, to
              monitor, edit, disclose, refuse to post, or remove at any time,
              for any reason in our sole discretion, any content anywhere on
              this Website. Notwithstanding this right, we do not and cannot
              review all content submitted to this Website. If notified, we may
              investigate an allegation that content transmitted to us is in
              violation of these Terms, and we will determine whether to have
              the communication removed. However, we are under no obligation to
              remove content and assume no responsibility or liability arising
              from or relating to any actions or content transmitted by or
              between you or any third party within or outside of this Website,
              including, but not limited to, any error, defamation, libel,
              slander, omission, falsehood, obscenity, pornography, profanity,
              danger, or inaccuracy contained therein.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              We may, in appropriate circumstances and at our sole discretion,
              terminate the access of users who infringe the copyrights of
              others or otherwise violate these Terms.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              If you believe that your work has been copied and is accessible on
              this Website in a way that constitutes copyright infringement, you
              may notify us by providing the following information (as required
              by the Online Copyright Infringement Liability Limitation Act of
              the Digital Millennium Copyright Act, 17 U.S.C. sec. 512):
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • a physical or electronic signature of the person authorized to
              act on behalf of the owner of an exclusive right that is allegedly
              infringed;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • identification of the copyrighted work claimed to have been
              infringed, or if multiple copyrighted works at this Website are
              covered by a single notification, a representative list of such
              works at this Website;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • identification of the material that is claimed to be infringing
              or to be the subject of infringing activity and that is to be
              removed or access to which is to be disabled, and information
              reasonably sufficient to permit us to locate the material;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • information reasonably sufficient to permit us to contact you,
              such as an address, telephone number, and if available, an e-mail
              address;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • a statement that you have a good faith belief that use of the
              material in the manner complained of is not authorized by you,
              your agent, or the law; and
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • a statement that the information in the notification is
              accurate, and, under penalty of perjury, that you are authorized
              to act on behalf of the owner of an exclusive right that is
              allegedly infringed.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Please send the written communication to our copyright agent by
              email and regular to:
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Email address: officialglowskin@gmail.com
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              E-mail Subject: “DMCA Request”
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              14. Links to Other Web Sites
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Our Service may contain links to third-party web sites or services
              that are not owned or controlled by Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin has no control over, and assumes no responsibility for,
              the content, privacy policies, or practices of any third-party web
              sites or services. You further acknowledge and agree that Glowskin
              shall not be responsible or liable, directly or indirectly, for
              any damage or loss caused or alleged to be caused by or in
              connection with use of or reliance on any such content, goods or
              services available on or through any such web sites or services.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              We strongly advise you to read the terms and conditions and
              privacy policies of any third-party web sites or services that you
              visit.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              15. Children
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              The website is intended for adults ages 18 and over. users under
              18 years old are prohibited from using the website for any
              purpose. By using this website, you represent that you are at
              least 18 years of age or of the age of majority in your state of
              residence.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              No one under age 13 may provide any information to or post any
              information on the Website We do not knowingly collect personal
              information from children under 13. If you are under 13, do not
              (a) use or provide any information on the Website or on or through
              any of its features, (b) register on the Website, (c) make any
              purchases through the Website, (d) use any of the interactive or
              public comment features of the Website, or (5) provide any
              information about yourself to us, including your name, address,
              telephone number, email address, or any screen name or user name
              you may use. If we learn we have collected or received personal
              information from a child under 13 without verification of parental
              consent, we will delete that information. If you believe we might
              have any information from or about a child under 13, please
              contact us at officialrustGlowskin@gmail.com.
            </p>
          </div>

          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              16. No warranties
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              This website is provided “as is” without any representations or
              warranties, express or implied. Glowskin makes no representations
              or warranties in relation to this website or the information and
              materials provided on this website. Without prejudice to the
              generality of the foregoing paragraph, Glowskin does not warrant
              that: this website will be constantly available, or available at
              all; or the information on this website is complete, true,
              accurate or non-misleading. Nothing on this website constitutes,
              or is meant to constitute, advice of any kind. If you require
              advice in relation to any legal, financial or medical matter you
              should consult an appropriate professional.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              17. Affiliation
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              We are in NO WAY affiliated with or endorsed by the FacePunch,
              Rust, Steam or any other trademarks of the Valve corporation. All
              trademarks are the property of their respective owners.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              18. Glowskin Wallet
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              By topping up an amount to your Glowskin wallet, you accept that
              the credits received (labeled by the $-sign) are not worth real
              money and not subject to any refunds.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              19. Returns and Refunds Policy
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              We do not issue refunds for digital products once the order is
              confirmed and the product is sent. We recommend contacting us for
              assistance if you experience any issues receiving or downloading
              our products. You may reach us via officialrustGlowskin@gmail.com.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              20. UI / Interface Errors
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Interface glitches/manipulation in no way entitles the user to a
              certain item. All outcomes are generated by our provably fair
              system and awarded as such. The user agrees that the outcome will
              be determined by the provably fair system outcome and any user
              interface errors do not entitle the user to that item.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              21. Bots and Steam API
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              The trade offer request sent by our bots are subject to Steam
              Guard authentication and the buyer must have Steam Guard activated
              for at least 15 days on their smartphone so the trade is
              completed. Note that this is a Steam restriction. The skins won't
              expire but the user need to wait for that period to end.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              22. Voice Over Internet Protocol (VOIP) Policy
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              All battles with VOIP are recorded by us. Recordings will never be
              listened to for moderation purposes. The only time recordings will
              be revisited is strictly for legal purposes and to enforce our
              rights under these Terms and Conditions. Recordings will not be
              shared with anyone outside of the Glowskin team, with the
              exception of legal purposes, such as in response to a subpoena.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              23. Governing Law; Disputes
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              All inquiries relating to the construction, validity, enforcement
              and interpretation of these Terms shall be governed by and
              construed and enforced in accordance with the laws of Cyprus.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              24. Limited License
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              We grant all Users a limited, nonexclusive, nontransferable
              personal license to access and use only Glowskin for private,
              non-commercial purposes on a single computer or mobile device. We
              also grant you a limited, nonexclusive, nontransferable personal
              license to access Glowskin, as limited by your additional purchase
              of certain paid features and upgrades. This paid license is for
              private, non-commercial purposes on a single computer or mobile
              device. Your license to access Glowskin is not a transfer of
              title. Glowskin and its licensors and service providers reserve
              and shall retain their entire right, title and interest in and
              Glowskin, including all copyrights, trademarks and other
              intellectual property rights therein or relating thereto, except
              as expressly granted to users in this Agreement.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              You will not copy or redistribute any materials from Glowskin, and
              you will prevent others from unauthorized access, use of, or
              copying. Users acknowledge and agree that they may not:
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              o Copy Glowskin, except as expressly permitted by this license;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              o Modify, translate, adapt or otherwise create derivative works or
              improvements, whether or not patentable, of Glowskin;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              o Reverse engineer, disassemble, decompile, decode or otherwise
              attempt to derive or gain access to the source code of Glowskin or
              any part thereof;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              o Remove, delete, alter or obscure any trademarks or any
              copyright, trademark, patent or other intellectual property or
              proprietary rights notices from Glowskin, including any copy
              thereof;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              o Rent, lease, lend, sell, sublicense, assign, distribute,
              publish, transfer or otherwise make available Glowskin or any
              features or functionality of Glowskin, to any third-party for any
              reason, including by making Glowskin available on a network where
              it is capable of being accessed by more than one device at any
              time;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              o Remove, disable, circumvent or otherwise create or implement any
              workaround to any copy protection, rights management or security
              features in or protecting Glowskin; or
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              o Use Glowskin in a manner prohibited by applicable laws or
              regulations, including, without limitation, in connection with any
              form of unlawful gambling.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              25. Other Intellectual Property Rights
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Copyright Information and Personal & Non-Commercial Use Limitation
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Content within Glowskin, including, without limitation, any
              technology, software products, accounts, names, logos, graphics,
              music, and virtual goods are owned and/or licensed by Glowskin and
              are protected by copyright, trade dress, patent, and trademark
              laws, international conventions, and other laws protecting
              intellectual property and related proprietary rights. Glowskin
              does not claim ownership of intellectual property owned by third
              parties.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Except as expressly permitted by this Agreement, Users must not
              reproduce, distribute, modify, create derivative works of,
              publicly display, publicly perform, republish, download, store or
              transmit any material available through Glowskin. In addition,
              Users must not:
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Modify copies of any materials available through Glowskin;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Reprint or electronically reproduce any content available
              through Glowskin, in whole or in part;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Provide copyrighted or other proprietary content to Glowskin or
              make such content available through Glowskin without permission
              from the owner of such material or rights;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Delete or alter any copyright, trademark or other proprietary
              rights notices from copies of materials available through
              Glowskin; or
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Access or use for any commercial purposes any part of or
              materials available through Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Printing, copying, modifying, downloading, or otherwise using or
              providing any other person with access to any part of Glowskin in
              breach of this Agreement may result in the termination of a User’s
              Account, prohibition from using Glowskin, and/or legal action.
              Content owners may take criminal or civil action against Users for
              unauthorized use of intellectual property. Users agree to
              indemnify and hold Glowskin from any unauthorized or illegal
              conduct by Users or through the use of a User’s Account, via
              Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">• Trademarks</p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin owns has/may register trademarks for its many goods and
              services, including, without limitation, the associated graphics,
              logos and service marks and they may not be used without prior
              written consent of Glowskin.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              26. Rights of Publicity
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              By participating in Glowskin, you agree to the use by Glowskin of
              Your username, statements, biographical information, and city and
              state address for advertising and promotional purposes of
              Glowskin, including, without limitation, the Glowskin contests,
              worldwide, and in perpetuity, in any and all forms of media, now
              known or hereafter devised without compensation, review or
              approval rights, notification or permission, except where
              prohibited by law. Glowskin reserves the right to make public
              statements about the entrants and winner(s), on the Internet, in
              promotional materials or otherwise, prior to, during, or following
              a Contest. You agree that We may announce any winner’s name on
              Glowskin at any time in connection with the marketing and
              promotion of Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Ideas and Inventions
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              All comments, feedback, suggestions, ideas, and other submissions
              (“Ideas”) disclosed, submitted, or offered to Glowskin in
              connection with Your use of Glowskin shall be the exclusive
              property of Glowskin. You agree that unless otherwise prohibited
              by law Glowskin may use, sell, exploit and disclose the Ideas in
              any manner, without restriction and without compensation to You.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              27. Conduct on Service
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Users agree not to use Glowskin for any unlawful purpose or for
              any purpose that is prohibited by this Agreement. Users further
              agree not to:
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Engage in any illegal activity, including gambling, or the
              planning of any illegal activity;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Post or transmit, or cause to be posted or transmitted, any
              content that is infringing, libelous, defamatory, abusive,
              offensive, obscene, pornographic or otherwise violates the law or
              the rights of Glowskin its Users, or any third-party;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Threaten, harass, abuse, or otherwise intimidate any User(s);
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Send or cause to be generated any unwanted e-mail to any
              User(s);
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Inflict or cause to be inflicted in any manner whatsoever
              software viruses or any other code designed to interrupt, destroy,
              limit, or otherwise affect the functionality of any software or
              hardware or telecommunications equipment associated directly or
              indirectly with Glowskin;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Employ any automated means, including, without limitation, bots,
              scrapers, or spiders to access or participate in Glowskin for any
              purpose;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Using any artificial means to alter a User’s position in the
              Contests;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Improperly using support or complaint features of Glowskin or
              making false reports to Glowskin ;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Use Glowskin for any purpose other than that which is authorized
              in this Agreement or in a manner that violates any laws including
              intellectual property laws;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Seek to or in any way assist others in obtaining Account,
              password, or personal information from any User(s);
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Create a false identity, impersonate another person, or
              otherwise attempt to mislead any person as to the identity or
              origin of any communication;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Creating more than one (1) Account;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Selling or transferring an Account or any attributes related
              thereto; or
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Engaging in any other activity deemed by Glowskin to be in
              conflict with the spirit or intent of this Agreement.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • post or transmit, or cause to be posted or transmitted, any
              communication or solicitation designed or intended to obtain
              password, account, or private information from any Glowskin user;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • create or submit unwanted email (“Spam”) to any other Glowskin
              users;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • submit comments linking to affiliate programs, multi-level
              marketing schemes, sites repurposing existing stories or off-topic
              content;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • post, email, transmit, upload, or otherwise make available any
              material that contains software viruses or any other computer
              code, files or programs designed or functioning to interrupt,
              destroy, or limit the functionality of any computer software or
              hardware or telecommunications equipment;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • use any robot, spider, scraper, sniping software or other
              automated means to access Glowskin for any purpose without our
              express written permission. Additionally, you agree that you will
              not: (1) take any action that imposes, or may impose in our sole
              discretion an unreasonable or disproportionately large load on our
              infrastructure; (2) interfere or attempt to interfere with the
              proper working of the Service or any activities conducted on the
              Service; or (3) bypass any measures we may use to prevent or
              restrict access to the Service;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • use artificial means, including creating multiple user accounts,
              to inflate your position and standing with the Glowskin community;
              use unauthorized scripts; all authorized scripts will be made
              available through the Service prior to game entry;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • advertise to, or solicit, any user to buy or sell any products
              or Service, or use any information obtained from the Service in
              order to contact, advertise to, solicit, or sell to users without
              their prior explicit consent;
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • sell or otherwise transfer your profile; or
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Any use of Glowskin in violation of the foregoing constitutes a
              breach of this Agreement and may result in, among other things,
              Account suspension and/or termination, prohibition from using
              Glowskin, and/or legal action. Users understand that any attempt
              to deliberately damage Glowskin or undermine any Contest may also
              be a violation of criminal and/or civil laws and Glowskin reserves
              the right to seek damages and other remedies from any such person
              to the fullest extent permitted by law. If Users wish to report
              any abuses, inappropriate online conduct, or a violation of this
              Agreement, please forward all evidence of the same to
              officialglowskin@gmail.com.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              28. Limitations on Warranty and Liability
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              • Disclaimer of Warranties
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              USERS EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF Glowskin IS AT
              THEIR SOLE RISK. USERS FURTHER ACKNOWLEDGE AND AGREE THAT Glowskin
              IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. NEITHER
              Glowskin NOR ANY OF ITS PARENTS, SUBSIDIARIES, AFFILIATES,
              LICENSEES, LICENSORS, CONTRACTORS, AGENTS, CONTENT PROVIDERS,
              VENDORS, COMPONENT SUPPLIERS (BOTH HARDWARE AND SOFTWARE), AND/OR
              ANY THIRD-PARTY WHO PROVIDES PRODUCTS OR SERVICES PURCHASED FROM
              OR DISTRIBUTED BY Glowskin AS WELL THEIR RESPECTIVE OFFICERS,
              DIRECTORS, MEMBERS, MANAGERS, REPRESENTATIVES, EMPLOYEES,
              INVESTORS OR THE LIKE (COLLECTIVELY “PROVIDERS”), WARRANT THAT
              SERVICES AFFILIATED WITH Glowskin, INCLUDING, BUT NOT LIMITED TO,
              THE WEBSITE, AND THE CONTESTS AND SERVICES OFFERED THEREON, WILL
              BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES, WORMS, TROJAN
              HORSES, KEYBOARD LOGGERS, SPYWARE, ADWARE, MALWARE, HARMFUL OR
              MALICIOUS CODE, OR OTHER DEFECTS.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, Glowskin
              DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION,
              IMPLIED AND STATUTORY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS.
              Glowskin MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND,
              EXPRESS OR IMPLIED, AS TO THE OPERATION OF Glowskin, SECURITY OF
              Glowskin, AVAILABILITY OF ANY GOODS, SERVICES OR OFFERINGS OFFERED
              ON OR THROUGH Glowskin, OR THE INFORMATION, CONTENT, SERVICES,
              MATERIALS OR PRODUCTS, INCLUDED ON OR THROUGH Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              NEITHER Glowskin NOR ANY PROVIDER MAKES A WARRANTY AS TO THE
              RESULTS THAT MAY BE OBTAINED FROM THE USE OF Glowskin OR AS TO THE
              ACCURACY, RELIABILITY, OR CURRENCY OF ANY INFORMATION, CONTENT, OR
              SERVICES, PROVIDED ON OR THROUGH Glowskin. THE INFORMATION,
              PRODUCTS, AND SERVICES PUBLISHED ON OR THROUGH Glowskin MAY
              CONTAIN INACCURACIES OR TYPOGRAPHICAL ERRORS. NEITHER Glowskin NOR
              ANY PROVIDER SHALL BE RESPONSIBLE FOR ANY OPINIONS, VIEWS, ADVICE,
              STATEMENTS, OR USER CONTRIBUTIONS POSTED ON OR THROUGH THE
              Glowskin (INCLUDING, WITHOUT LIMITATION, IN ANY INTERACTIVE AREAS
              OF Glowskin) BY ANY PERSON OR ENTITY OTHER THAN AN AUTHORIZED
              Glowskin REPRESENTATIVE.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Limitations on Liability
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Neither Glowskin nor the providers guarantee the continuous,
              uninterrupted, or secure access to Glowskin or any aspect thereof.
              the operation of Glowskin may be interfered with by numerous
              factors outside the control of Glowskin. you understand and agree
              that neither Glowskin nor the providers shall be liable to users
              for any indirect, incidental, special, consequential, or exemplary
              damages, including, without limitation, damages for loss of
              profits, goodwill, use, data or other intangible losses (even if
              Glowskin or the providers had been advised of the possibility of
              such damages), resulting from: (i) the use or the inability to use
              Glowskin; (ii) unauthorized access to or alteration of user
              transmissions or data; (iii) opinions, views, advice, statements,
              or user contributions posted on or through Glowskin; or (iv) any
              other matter relating to Glowskin. notwithstanding anything to the
              contrary contained herein and regardless of the form of the
              action, Glowskin’s liability to users for any cause whatsoever
              will at all times be limited to the amount paid, if any, by such
              user to Glowskin for use of Glowskin during the term of their
              registration, not including any fees paid for services and/or
              products rendered prior to the circumstances giving rise to the
              claim.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              in the event that a user resides in a jurisdiction that does not
              allow the exclusion of certain warranties, or the limitation or
              exclusion of liability for incidental or consequential damages
              some of the limitations above may not apply to such user.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              29. Service and Maintenance
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin conducts maintenance work on its systems from time to
              time primarily for the purpose of ensuring security and integrity.
              A portion, or sometimes all, of the features of Glowskin may not
              be available during maintenance periods. Users will generally be
              notified of maintenance periods in advance; however, Users hereby
              agree that Glowskin may update Glowskin with or without notifying
              Users. Glowskin also reserves the right to modify or discontinue
              operation of any aspect of Glowskin at any time, including,
              without limitation, the availability of the Website, or any
              features or content thereon, including without limitation the
              offering of the contests. Glowskin may also impose limits on
              certain features and offerings or restrict access to parts or all
              of Glowskin with or without notice to Users and without liability
              to Users or any third-party. All problems encountered during the
              use of Glowskin, including those with regard to User Accounts,
              etc., can be reported to Glowskin at
              officialrustGlowskin@gmail.com.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md">
            <div className="text-white text-2xl font-bold pt-2 ">
              30. Disputes
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              In the event of any dispute arising between Rust Glowskin
              Entertainment and you, the parties will make best efforts to solve
              such dispute in good faith within a reasonable time. In case that
              you and Glowskin will not reach an amicable solution within a
              reasonable period (of no less than 30 days as of the commencement
              of the amicable dispute resolution process), you or Glowskin may
              seek legal resolution with the competent courts situated in
              Cyprus, and such courts shall have sole and exclusive jurisdiction
              to resolve such dispute[1] [2] [3] .
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Alternative Binding Arbitration and Class Action Waiver
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Dispute Resolution; Arbitration and Governing Law
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              In case of any dispute arising between Glowskin and you, the party
              raising the dispute shall issue a written notice to the other
              party. In case the notice is to be issued to you, sending the
              notice to the email address registered with Glowskin shall
              constitute delivery. A notice to be issued to Glowskin is to be
              served on officialglowskin.com.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              On receipt of the said notice, the parties shall first try to
              resolve the dispute amicably through discussions. In the event
              that the parties are unable to resolve the dispute within thirty
              (30) days of receipt of the notice, the dispute shall be referred
              to and thereafter settled by arbitration as provided here.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              If the dispute cannot be resolved amicably, you agree to finally
              settle all disputes only through arbitration; provided, however,
              that Glowskin shall be entitled to seek injunctive or equitable
              relief in the state and federal courts in Cyprus and any other
              court with jurisdiction over the parties. The pursuit of such
              equitable or injunctive relief shall not constitute a waiver on
              the part of Glowskin to pursue any remedy for monetary damages.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              With respect to any dispute arising out of or related to these
              terms, including without limitation disputes related to Glowskin:
              (i) you hereby expressly give up your right to have a trial by
              jury; and (ii) you hereby expressly give up your right to
              participate as a member of a class of claimants in any lawsuit,
              including but not limited to class action lawsuits involving any
              such dispute.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              In arbitration, there is no judge or jury and review is limited.
              The arbitrator’s decision and award are final and binding, with
              limited exceptions, and judgment on the award may be entered in
              any court with jurisdiction. The parties agree that, except as set
              forth above, any claim, suit, action or proceeding arising out of
              or relating to Glowskin, or these terms, shall be resolved solely
              by binding arbitration before a sole arbitrator under the
              streamlined Arbitration Rules Procedures of JAMS Inc. (“JAMS”) or
              any successor to JAMS. In the event JAMS is unwilling or unable to
              set a hearing date within fourteen (14) days of the filing of a
              “Demand for Arbitration”, then either party can elect to have the
              arbitration administered by the American Arbitration Association
              (“AAA”) or any other mutually agreeable arbitration administration
              service. If an in-person hearing is required, then it will take
              place in Cyprus. The federal or state law that applies to these
              Terms of Service Cyprus will also apply during the arbitration.
              Disputes will be arbitrated only on an individual basis and will
              not be consolidated with any other proceedings that involve any
              claims or controversy of another party, including any class
              actions; provided, however, if for any reason any court or
              arbitrator holds that this restriction is unconscionable or
              unenforceable, then the agreement to arbitrate doesn’t apply and
              the dispute must be brought in a court of competent jurisdiction
              in New York County, New York. Glowskin agrees to pay the
              administrative and arbitrator’s fees in order to conduct the
              arbitration (but specifically excluding any travel or other costs
              of participant to attend the arbitration hearing). Either party
              may, notwithstanding this provision, bring qualifying claims in
              small claims court.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              The Federal Arbitration Act shall govern the interpretation,
              enforcement and all proceedings at such arbitration and judgment
              upon such arbitration award may be entered in any court having
              jurisdiction. All participants agree to abide by the terms of
              these Terms of Service. Each party agrees to service of process by
              mail or other method acceptable under the laws of the State of New
              York. You hereby waive any rights or claims to attorney's fees,
              indirect, special, punitive, incidental or consequential damages,
              whether foreseeable or not and whether based on negligence or
              otherwise. In no event will Glowskin be liable to any person or
              entity for any direct, special incidental, exemplary, punitive or
              consequential damages (including loss of use, data, business or
              profits) arising out of or in connection with any person or
              entity’s use or inability to use Glowskin whether such liability
              arises from any claim based upon contract, warranty, tort
              (including negligence), strict liability or otherwise, and whether
              or not Glowskin has been advised of the possibility of such loss
              or damage. Some jurisdictions do not allow the limitation or
              exclusion of liability for incidental or consequential damages, so
              the above limitation or exclusion may not apply to you.
            </p>
          </div>

          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md ">
            <div className="text-white text-2xl font-bold pt-2 ">
              31. Withdrawal Rules
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              Only prizes can be withdrawn, not deposits. Gems must be fully
              wagered before they can be withdrawn via either prizes or
              cryptocurrency. Withdrawals may only be made to the end user, and
              not third parties. Know Your Customer procedure is mandated for
              crypto withdrawals originating fiat deposits.
            </p>
          </div>
          <div className="bg-btnDark opacity-90 mt-5 px-4 py-2 rounded-md mb-5">
            <div className="text-white text-2xl font-bold pt-2 ">
              32. General Provisions
            </div>
            <p className="text-white text-opacity-50 w-full  ">
              • Relationship of Parties/No Third-party Beneficiaries
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Users agree that no joint venture, partnership, employment, or
              agency relationship exists between Users and Glowskin as a result
              of this Agreement or their use of Glowskin. Users agree not to
              hold themselves out as representatives, agents, operators,
              distributors, or employees of Glowskin and Glowskin shall not be
              liable for any of their representations, acts, or omissions. Users
              also agree that, except as otherwise expressly provided in this
              Agreement, there shall be no third-party beneficiaries to this
              Agreement.
            </p>
            <p className="text-white text-opacity-50 w-full  ">• Assignment</p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin may assign its rights and obligations under this
              Agreement and/or the Glowskin Privacy Policy, in whole or in part,
              to any person or entity at any time with or without the Users’
              consent. Upon such assignment, Glowskin may be relieved of any
              further obligation hereunder. Users may not assign or delegate any
              rights or obligations under this Agreement or the Privacy Policy
              without Glowskin’s prior written consent, and any unauthorized
              assignment and delegation by Users is void and ineffective.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Circumvention/Indemnification
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Users agree that they shall not circumvent or attempt to
              circumvent these Terms or Glowskin or otherwise interrupt or
              attempt to interrupt the operations of Glowskin (collectively, a
              “Circumvention Act”). If Glowskin determines, at its sole
              discretion, that Users have engaged, or attempted to engage, in
              any Circumvention Act, or to otherwise commit fraud with regard to
              Glowskin, then, in such an event, Glowskin reserves the right to
              institute civil or criminal proceedings against such Users and to
              report such Users to the relevant regulatory authorities.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Users further agree to indemnify, save, and hold harmless Glowskin
              and the Providers from any claims, losses, damages, liabilities,
              including legal fees and expenses, arising out of their use or
              misuse of Glowskin, any violation by Users of this Agreement, or
              any breach of the representations, warranties, and covenants made
              by Users herein. Glowskin reserves the right, at the Users’
              expense, to assume the exclusive defense and control of any matter
              for which the Users are required to indemnify Glowskin, and Users
              agree to cooperate with Glowskin’s defense of these claims.
              Glowskin will use reasonable efforts to notify Users of any such
              claim, action, or proceeding upon becoming aware of it. Users
              agree that the provisions in this paragraph will survive any
              termination of their Glowskin Account or of Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Force Majeure
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              Glowskin shall not be liable for any delay or failure to perform
              resulting from unforeseen circumstances or causes outside its
              reasonable control, including, without limitation, acts of God,
              war, terrorism, riots, embargoes, acts of civil or military
              authorities, fire, floods, accidents, network infrastructure
              failures, strikes, or shortages of transportation facilities,
              fuel, energy, labor or materials.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Waiver/Severability
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              No failure or forbearance on Glowskin’s part to exercise its
              rights or insist upon performance of obligations hereunder is to
              be construed as a waiver or relinquishment of those or any other
              rights or obligations in that or any other instance; rather, the
              same shall remain in full force and effect. If any provision of
              this Agreement is deemed unlawful, void, or for any reason
              unenforceable, such provision shall be narrowed in scope or
              otherwise amended to the extent necessary to make such provision
              lawful, valid and enforceable while as nearly as possible
              reflecting the intent of the parties as expressed in this
              Agreement, or, if such amendment is impossible, severed from this
              Agreement. No amendment or severing of any provision of this
              Agreement shall affect the validity or enforceability of any
              remaining provisions.
            </p>

            <p className="text-white text-opacity-50 w-full  ">
              • Entire Agreement
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              These Terms constitute the entire agreement between Users and
              Glowskin with respect to the subject matter hereof and supersedes
              and replaces all prior or contemporaneous understandings or
              agreements, written or oral, regarding such subject matter. Any
              waiver of any provision of these Terms or the Glowskin Privacy
              Policy will be effective only if in writing and signed by
              Glowskin.
            </p>
            <p className="text-white text-opacity-50 w-full  ">
              • Supplemental Policies
            </p>
            <p className="text-white text-opacity-50 w-full ">
              Glowskin may publish additional policies related to specific
              services such as contests, tournaments, or promotions. Your right
              to use such services is subject to those specific policies and
              these Terms.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
